# Generated by Django 3.1.7 on 2022-02-22 12:03

import ciphers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('answer', models.CharField(max_length=256)),
                ('crossword', models.ImageField(null=True, upload_to=ciphers.models.upload_location)),
                ('hint', models.FileField(blank=True, null=True, upload_to=ciphers.models.upload_location)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('modal', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
