# Generated by Django 3.1.7 on 2022-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedsurface6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image1',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=1, max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='closedsurface6/'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
