# Generated by Django 3.1.7 on 2022-02-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.IntegerField(default=1)),
                ('question', models.TextField(blank=True)),
                ('answer', models.CharField(max_length=256)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='meseum5/')),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('modal', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
