# Generated by Django 3.1.7 on 2022-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum5', '0003_auto_20220226_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
